version: "3.4"
networks:
  public:
  catalog:
  iam: 
  invoicing:
  backend: 
volumes:
  message-broker: 
services:
  api-gateway: 
    # image: gcr.io/invoicing3/api-gateway:dev
    build: 
      context: ./../api-gateway
      dockerfile: ./Dockerfile
    volumes:
      - "./../api-gateway:/app"
    networks:
      - public
    ports: 
      - 3000:3000
    environment:
      CATALOG_MICROSERVICE_HOST: catalog
  catalog: 
    build: 
      context: ./../catalog
      dockerfile: ./Dockerfile
    networks:
      - public
      - catalog
    volumes:
      - "./../catalog:/app"
  catalog-db: 
    image: mongo:latest
    networks: 
      - catalog
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
    networks:
      - backend
      - public
  kafka:
    image: obsidiandynamics/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    networks:
      - backend